### ISSUE TITLE
Consider using standard verbs for your cmdlets

### ISSUE THREAD

**Issue by jhoek** [rvanbekkum/ps-xliff-sync#10]
Microsoft strongly encourages PowerShell developers to follow certain guidelines when it comes to naming cmdlets to facilitate their discoverability. Use `Get-Verb` in PowerShell to get a list of approved verbs and their typical usages. 

Since your module is already published, changing your cmdlet names now may break existing user scripts. However, what you may want to consider is to change your cmdlet names to comply with Microsofts guidelines, and, where appropriate, give each cmdlet a so called alias that contains the old, non-compliant name. That way, user scripts will not be broken.

**Comment by rvanbekkum** [comment]
Thank you for filing the issue. I will have a look at that as well. Do you have certain suggestions for cmdlet-names?

**Comment by jhoek** [comment]
Sync-XliffTranslations and Get-XliffTranslations already comply with Microsoft's guidelines. Check-XliffTranslations should perhaps be called Test-XliffTranslations.

**Comment by jhoek** [comment]
For Trans-XLiffTranslations, I would consider the verbs Set or Update? Also, nouns in cmdlet names should be singular, so when introducing new names and aliases, you could consider giving the official cmdlet names singular nouns.

**Comment by rvanbekkum** [comment]
Changes for this have been shipped in the newly release, version 1.3.0.
