### ISSUE TITLE
Powershell Gallery

### ISSUE THREAD

**Issue by aptMattKoe** [rvanbekkum/ps-xliff-sync#11]
I realy like this whole project!
Is there an opportunity to host this on Powershell Gallery to "install-Module" it? :)

**Comment by rvanbekkum** [comment]
Hi @aptMattKoe,
Nice to hear that you like it! 😊 It's already available actually:
https://www.powershellgallery.com/packages/XliffSync

Maybe I can make this more clear in the README then? 🙂

**Comment by aptMattKoe** [comment]
oh, cool!
It would be great if there is an Installation Part in the ReadMe :)
Kind like this:
https://github.com/fariapp/fari-app#installation

**Comment by rvanbekkum** [comment]
I've added a section to the README with an Installation instruction. 😊
