### ISSUE TITLE
Check-XliffTranslations should have a parameter to suppress detailed info about missing/problematic translations

### ISSUE THREAD

**Issue by Aize-S** [rvanbekkum/ps-xliff-sync#12]
Running Check-XliffTranslations you always get the details about the missing/problematic translations. Using it in DevOps pipelines or some other process you may not always be interested in all this info. Just knowing that there are missing/problematic translations in the file is sometimes enough.

**Comment by rvanbekkum** [comment]
Thanks for the suggestion, I will include this in the next update, which I will continue working on soon. 🙂

**Comment by rvanbekkum** [comment]
Hi @Aize-S,
I just realized, you might just want to take the return value and assign it to a variable, like this:
```powershell
$unitsWithProblems = Check-XliffTranslations ...
```
It was not described yet, but the return value of the function are the translation units for which problems are detected. If you don't assign the return value to a variable, then these units will be printed.
Does assigning the return value to a variable work for you to fix this for you?
