### ISSUE TITLE
Test-XliffTranslations: don't append items to existing arrays

### ISSUE THREAD

**Issue by jhoek** [rvanbekkum/ps-xliff-sync#18]
In `Test-XliffTranslations`, you append (potentially numerous) items to the `$missingTranslationUnits` and `$needWorkTranslationUnits` arrays. In PowerShell (.NET), this is an expensive operation (increasingly so for larger arrays) that can easily be avoided by capturing the items emitted (i.c. by the ForEach-Object command), then storing them in an array all at once. 

Please consider the performance difference in the (admittedly simple) example below. 

![CleanShot 2021-11-23 at 14 18 03@2x](https://user-images.githubusercontent.com/1273387/143031207-84611e22-616a-44e6-8844-a7a67980a846.png)

**Comment by jhoek** [comment]
The same appears to apply to the return value of `Test-XliffTranslations`: 

    return $missingTranslationUnits + $needWorkTranslationUnits;

Instead of combining the two existing arrays into a newly allocated array that you subsequently return, please consider returning the arrays separately, one after the other.


<img width="519" alt="CleanShot 2021-11-23 at 15 01 48@2x" src="https://user-images.githubusercontent.com/1273387/143038355-a4907c6d-f86d-47cc-a446-a076764c2817.png">

**Comment by jhoek** [comment]
In order to use the logic from my first example above, you'd probably have to loop through the translation units twice - once to capture missing entries, and once for capturing entries with problems. Looping twice, of course, comes at a certain performance cost as well, so in this case, we may be better off collecting entries in a collection of a type that does not require reallocation when adding items. My personal preference, for type safety reasons, would be to use a generic List.

When a List is written to the output stream, it is automatically unraveled, as you can read here: https://stackoverflow.com/questions/38257354/preserving-powershell-function-return-type. This means that the output type (i.c. the XML node that represents the translation unit) will remain the same as before.

**Comment by rvanbekkum** [comment]
Shipped in version 1.5.0.0
