### ISSUE TITLE
When using Test-XliffTranslations from Azure Devops, we don't care about the translation units

### ISSUE THREAD

**Issue by jhoek** [rvanbekkum/ps-xliff-sync#20]
Standard PowerShell cmdlets whose return value is, in most use cases, irrelevant tend to have a `-PassThru` parameter. Only if this switch parameter is set will the cmdlet write objects to the output stream. 

Test-XliffTranslations, when used from Azure Devops, reports its findings in the pipeline's log. Only rarely will anybody be interested in the returned translation units in that scenario. Perhaps you would consider adding a new `-PassThru` parameter as a condition for returning `$missingTranslationUnits` and `$needWorkTranslationUnits`? 

(Until then, I'll just pipe the results to Out-Null.)

**Comment by rvanbekkum** [comment]
Thanks, did not know that. Would be a nice enhancement.

**Comment by jhoek** [comment]
@rvanbekkum I'm going to close this issue. Thinking about it some more, I think the advantage of avoiding output does not outweigh the disadvantage of changing the default behaviour (with -PassThru in place, Test-XliffTranslations would only produce output if the switch is set), thus potentially breaking user scripts. As I said, I'll simply pipe the output to Out-Null for now.
