### ISSUE TITLE
Error when using Test-BcAppXliffTranslations in Azure Pipeline

### ISSUE THREAD

**Issue by frottke** [rvanbekkum/ps-xliff-sync#36]
Currently I get the following error when I run Test-BcAppXliffTranslations in my pipeline. Below is the YAML step and the error message from the log

____________________________________________________________
Where-Object : The property 'Name' cannot be found on this object. Verify that the property exists.
At C:\Program 
Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.6\AppHandling\Sort-AppFoldersByDependencies.ps1:125 char:13
+     $apps | Where-Object { $_.Name -eq "Application" } | ForEach-Obje ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Where-Object], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Microsoft.PowerShell.Commands.WhereObjectCommand

____________________________________________________________

YAML Step after "Run Pipeline"

____________________________________________________________
  - task: PowerShell@2
    displayName: 'Check Translations'
    inputs:
      targetType: 'inline'
      script: |
        Install-Module BCContainerhelper -force
        Install-Module XliffSync -force
        Test-BcAppXliffTranslations -AzureDevOps 'error' -printProblems 
____________________________________________________________

I'm (unfortunately) able to reproduce that error locally on my machine in various repositories and folder structures

**Comment by rvanbekkum** [comment]
This function uses the Sort-AppFoldersByDependencies command of the BcContainerHelper module and with that assumes the following folder structure:

* Root
  * App
      * Translations
          * *.g.xlf
          * *.nl-NL.xlf
          * ...
      * app.json
      * ...
   * App2
      * Translations
          * *.g.xlf
          * *.nl-NL.xlf
          * ...
      * app.json
      * ...
  * ...

If this does not apply to how you set up your repository, then the function might run into an error.

Please let me know if this answers your question.

**Comment by frottke** [comment]
Hi @rvanbekkum,

thank you for your fast reply!

We do have the following structure:

- Root
  - App1
    - Translations
      - *.g.xlf
      - *.nl-NL.xlf
    - app.json
  - App2
    - Translations
      - *.g.xlf
      - *.nl-NL.xlf
    - app.json


I also tried the following command with the parameter "AppFolders" with various paths in an trial & error attempt:
Test-BcAppXliffTranslations -AzureDevOps 'error' -printProblems -AppFolders @("App1")

**Comment by rvanbekkum** [comment]
I see you don't have a `-buildProjectFolder` parameter. Could you see if you could set it explicitly to the root folder of your repository? Also note that the `-appFolders` parameter expects folder names only, e.g., `@("App1", "App2")`.

**Comment by frottke** [comment]
I got it working with the `-buildProjectFolder` parameter. Thank you very much!


I do have a suggestion regarding the error handling when `$azureDevOps -eq 'error'`:

```
if (($AzureDevOps -eq 'error') -and ($issueCount -gt 0)) {
    throw "$issueCount issues detected in translation files!"
    Write-Host "##vso[task.logissue type=error]$issueCount issues detected in translation files!"
```

That way, we would avoid that powershell exits with code '1' . I'll create an pull request 👍

**Comment by rvanbekkum** [comment]
> That way, we would avoid that powershell exits with code '1' . I'll create an pull request 👍

For our pipelines we have actually configured it to fail the build pipeline when issues are detected. Maybe you know something to make that possible without a `throw`-statement, or can take it into account in your PR? 😉

**Comment by frottke** [comment]
> For our pipelines we have actually configured it to fail the build pipeline when issues are detected. Maybe you know something to make that possible without a throw-statement, or can take it into account in your PR? 😉

->pull request https://github.com/rvanbekkum/ps-xliff-sync/pull/37
